### ISSUE TITLE
Placeholder for deploying, testing and filling the new PROD server with experiments

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1014]
### ⚠️ Should happen before June 30, 2024! ⚠️
- [x] Add environment variables in Github for new domain => Done ( hopefully correctly :-) ) [See here](https://github.com/Amsterdam-Music-Lab/MUSCLE/settings/environments/2949949021/edit)
- [x] Update `podman.yml` with new job => WIP. See also #1015 
- [x] Deploy application to new Production server, aka [illc-aml-mu-prd.science.uva.nl](illc-aml-mu-prd.science.uva.nl) => WIP. See also #1015 
- [x] Download uploads from old PROD
- [x] Upload uploads to new PROD
- [x] Export database dump from old PROD
- [x] Import database dump to new PROD
- [x] Request DNS change
- [x] After DNS confirmation test & confirm everything works as expected on app.amsterdammusiclab.nl

Template copied from #853

**Comment by BeritJanssen** [comment]
The problem (caused by a volume taking more space than allocated) is fixed, DNS has been switched to the new server.
