### ISSUE TITLE
🐛 [BUG] - Experiments not loading in Safari

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#1040]
### Description

Although Firefox and Chrome seem to be OK, all experiments are failing in Safari (including all iOS devices) with the message 'An error occurred while loading the data, please try to reload the page. (Error: next_round_data unavailable) 

### Screenshots

![image](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/1194840/baf7cc30-bcda-4faa-a519-9582713b6f8e)

### Reproduction URL

https://app.amsterdammusiclab.nl/thats_my_song

### Reproduction steps

```bash
1. Go to any of our experiments using the Safari browser.
```

### Browsers

Safari

**Comment by drikusroor** [comment]
Closing this as:

> The API url configured for the frontend was still pointing to the old temporary domain of illc-aml-mu-pr.science.uva.nl. This URL still works and also points to the same backend. The frontend/browser, approached with app.amsterdammusiclab.nl then makes requests to illc-aml-mu-pr.science.uva.nl. Chrome/Firefox apparently allow this, maybe because they share the same IP and are connected through DNS, but Safari doesn't and subsequently refuses to set the CSRF cookie, resulting in many requests (that depend on getting the participant from the DB) failing.
> 
> So, my Safari was also having issues with S2S. But now, after updating the API url to app.amsterdammusiclab.nl/server for the frontend, it seems to work as it should.
