### ISSUE TITLE
That’s My Song ‘Play Again’ button fails to load experiment

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#1046]
### Description

The title says it all: at the end of a That’s My Song round, the Play Again button brings up a screen with the error message that the experiment cannot be loaded. 

### Reproduction steps

```bash
1. Play a complete That’s My Song round 
2. Click on 'Play Again' on the trophy screen
```

### Browsers

Safari

### OS

Mac

### Additional context

Could we add iOS and Android to the list of platforms?

## Drikus' notes

Link from backend seems to be valid:

```json
"button": {
  "text": "Play again",
  "link": "https://acc.amsterdammusiclab.nl/thats_my_song?participant_id=test"
}
```

However, the frontend uses React Router's `Link' component, which expects a relative path instead of an absolute url. It subsequently prefixes the url with a slash `/`.

<img width="1004" alt="image" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/8208970/aee8a66e-c24a-416a-a142-8fb9cf459470">

### Proposed solution

- For Play Again, only send relative urls (that's my song & hooked) from the backend.
- Depending on whether the Final actions' button link is a relative path or an absolute url, render a `Link` component or render an achor tag (`<a href...>`) for the absolute urls.

**Comment by drikusroor** [comment]
Closed per #1051
