### ISSUE TITLE
Toontje Hoger styling adjustments: Absolute / Tempo

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1057]
## Requirements

- Playbuttons' border color extends as background color to the underlying labels
- The second play button should be orange
- Choice buttons [A] & [B] should be smaller

**Comment by BeritJanssen** [comment]
Is:
<img width="486" alt="Screenshot 2024-06-04 at 13 46 45" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/11174072/8f960dfb-3fcd-4c6f-96d4-deede55cd2fb">
Should be:
<img width="387" alt="Screenshot 2024-06-04 at 13 45 20" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/11174072/dcaaf5ed-2f99-4f1d-8df9-6863cc61070f">
