### ISSUE TITLE
🐛 [BUG] - That's My Song "Play Again" button loads an error

### ISSUE THREAD

**Issue by Mbali-M** [Amsterdam-Music-Lab/MUSCLE#1083]
### Description

At the end of the That's My Song round, when the "Play Again" button is clicked (on the score page), "Error: Could not load experiment" is still coming up. The IOS of all iPads is up to date (v 17.5.1). The correct wifi was used and the connection was stable

![Amsterdam Music Lab Experiment](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/172078654/f74c7aec-9c28-4663-8084-b645675e9670)

### Reproduction steps

```bash
1. Play a complete That's My Song round
2. Click on "Play Again" on the trophy screen
3. See error
```

### Browsers

Safari

### OS

Mac

**Comment by drikusroor** [comment]
Probably related to #1046

**Comment by drikusroor** [comment]
@Mbali-M I've release [v2.1.4](https://github.com/Amsterdam-Music-Lab/MUSCLE/releases/tag/v2.1.4) and confirmed that the Play Again button in [That's my song](https://app.amsterdammusiclab.nl/thats_my_song?participant_id=test) works as expected again. Could you confirm this a well?

**Comment by Mbali-M** [comment]
I can confirm that That's My Song is working as expected. Thank you very much!

**Comment by drikusroor** [comment]
> I can confirm that That's My Song is working as expected. Thank you very much!

Thanks for checking! 🙏 I'll close the issue now
