### ISSUE TITLE
question_series in Base

### ISSUE THREAD

**Issue by albertas-jn** [Amsterdam-Music-Lab/MUSCLE#1094]
Think about if `question_series` should be defined in `Base`. It adds question series to experiments that don't need to ask any questions (Toontjehoger). Otherwise, assign `question_series=[]` in extended classes.

**Comment by BeritJanssen** [comment]
I included a commit to remove the `question_series` from `base.py` while working on #847. I need to go over all rules files for that issue, in order to check which session methods they call, and it kind of itched in my fingers to go ahead and remove it.

**Comment by albertas-jn** [comment]
OK, but it should not be completely removed, but set to an empty list. I'd also keep the current `question_series` as a comment/doc in the file just as an example how it can be done if `base.py` is ever used as a template.
