### ISSUE TITLE
Allow ordering of logos in theme footer

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1121]
Right now, logos are added in the order of their pk in the database. It would be good if there was a more elegant way to control their ordering.

**Comment by drikusroor** [comment]
We can do it the very simple way: Add a sort number to the Image model, but this can have nasty side effects if you are using the image in several places

Another way might be: Footer.logos -> SortedImage (with sort prop) -> Image

A more complex but generic way might be to introduce ImageGalleries:

Footer.logos -> ImageGallery -> ImagegalleryImage (with sort prop) -> Image

**Comment by BeritJanssen** [comment]
I was also thinking of sorting by name, which can be done quite easily. I do think we'll deal with logos being reused, which would mean we would have to add multiple copies of the same image. On the other hand, it's unlikely that whole logo sets will be reused.

So I think the implementation of a `OrderedImage` or similar would be best. NB I think we should always call ordering fields `index`, as it's clearest that lower == first.

**Comment by drikusroor** [comment]
> I was also thinking of sorting by name, which can be done quite easily. I do think we'll deal with logos being reused, which would mean we would have to add multiple copies of the same image. On the other hand, it's unlikely that whole logo sets will be reused.
> 
> So I think the implementation of a `OrderedImage` or similar would be best. NB I think we should always call ordering fields `index`, as it's clearest that lower == first.

I did a bit of research and I did fin a potential problem. If we use a model `OrderedImage`, it will de facto be the many to many model that already exists now, but with an index. This means that the model will have an FK to `FooterConfig`, e.g.:

```py
class OrderedImage(models.Model):
    footer_config = models.ForeignKey(FooterConfig, on_delete=models.CASCADE)
    image = models.ForeignKey('image.Image', on_delete=models.CASCADE)
    index = models.PositiveIntegerField()
```

This will then also mean that we cannot use `OrderedImage` generically for potential other ordered images on other models. Is that okay or do we want it to be more generic?

If we do want it to be reusable for other models in the future, we can go for the earlier mentioned `ImageGallery` option, or we can use Django's "GenericForeignKey" in combination with a "ContentType":

```py
class OrderedImage(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE) # This will be the FK of the FooterConfig model (not the object)
    object_id = models.PositiveIntegerField() # This will be the FK of the FooterConfig object
    content_object = GenericForeignKey('content_type', 'object_id')
    image = models.ForeignKey('image.Image', on_delete=models.CASCADE)
    index = models.PositiveIntegerField()

    class Meta:
        ordering = ['index']
        unique_together = (('content_type', 'object_id', 'image'),)
```

**Comment by BeritJanssen** [comment]
Thanks for digging into this! I don't see a need for an `ImageGallery` at this point. I think the `OrderedImage` approach is fine. As it's specific for the footer with logos, we can also call it "LogoImage" then. Or perhaps even "SponsorImage", to distinguish it from the logo of the website itself - during setup of ToontjeHoger I got sometimes confused by this, that we now use "logo" both for the website logo and the logo of sponsors.
