### ISSUE TITLE
Delete unused Block fields

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1133]
After #973
- [ ] block.title no longer required but optional (is not necessary per se, except for when you use dashboard)
- [ ] remove block.consent field (is on experiment level now)
- [ ] remove block.active field (we can use the `active` field on an experiment level to deactivate the whole experiment)
~- remove block.slug field~

**Comment by drikusroor** [comment]
>  remove block.slug field

Will `slug` not be used anymore at all?

**Comment by BeritJanssen** [comment]
I thought we might use `id` instead, to avoid confusion with handling slugs at different levels.
