### ISSUE TITLE
Proposal: remove `GroupedBlock` model

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1134]
Instead of using a separate `GroupedBlock` model, we might already give the `Block` model itself an `index` field.

*Advantage*: admin users need to navigate less models
*Disadvantage*: `Block` objects cannot be reused, using the same block in different experiment phases will mean users will have to create duplicate data

As the admin form for `Experiment` should eventually support creating inline `Block` objects, in practice this will mean admin users will probably create new objects.

Steps:
- [x] add `index` field to `Block` model
- [x] create migration file
- [x] write a data migration which moves indices from `GroupedBlock` to `Block.index` (including backwards migration), and optionally creates new objects if there are multiple `GroupedBlock`s linked to the same `Block`
  - [x] try to avoid slug conflicts whenever blocks have to be duplicated 
  - [x] make sure index information is copied in migration too
- [x] remove `GroupedBlock` model
- [x] create migration file to delete the model from the database

**Comment by drikusroor** [comment]
> using the same procedure in different experiments will mean users will have to create duplicate data

Is this also the reason of adding issue #1136 ? :-) I'm not for or against the idea of simplifying the models, as long as the admin interface is intuitive enough to re-use / duplicate a procedure. Is it maybe an idea to sketch the admin interface we would like to see, or were you already thinking of the inline form that comes with adding a FK to Phase to the Procedure model?
