### ISSUE TITLE
Redesign admin interface after refactor

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1135]
After #1133.

The admin interface, after the refactor, should provide users with the following utilities:
~~- [ ] when creating an experiment, auto-create phase & block within it~~
- [x] #1192
  - If possible, we can use nested inline forms. See also #1188 for how you can use `django-nested-admin` to do that.

For the latter, much of the logic of the current `ExperimentCollection` admin can be reused

Update: after the phase / block are nested inlines, we can probably achieve a cleanish admin interface if we do the following:
In principle, with the inline forms for phase & block, everything's already in pretty good working shape.
Some things to change:
- [ ] Remove "Name" from the Phase. I think Phases should be pretty easy to see at a glance with the blocks which are inside it.
- [ ] Turn the inline block's `playlists' field into a checkbox selection
- [x] Turn the inline block's `rules` field into a dropdown
- [ ] Remove `Phase` and `Block` forms altogether? I think in the long run, we want to manage this all inline in the `Experiment` form, so to avoid clutter and confusion, I would argue we can unregister `Phase` and `Block` models from the admin interface.

**Comment by drikusroor** [comment]
> when creating an experiment, auto-create phase & block within it

Do you mean that the empty form for a phase and block will be displayed already?

**Comment by BeritJanssen** [comment]
> > when creating an experiment, auto-create phase & block within it
> 
> Do you mean that the empty form for a phase and block will be displayed already?

Yes, exactly.

**Comment by BeritJanssen** [comment]
On closer inspection, it's probably not too useful to auto-create objects when opening the form, as this sets defaults, which may do more harm than good.

In principle, with the inline forms for phase & block, everything's already in pretty good working shape.
Some things to change:
- [ ] Remove "Name" from the Phase. I think Phases should be pretty easy to see at a glance with the blocks which are inside it.
- [ ] Turn the inline block's `playlists' field into a checkbox selection
- [ ] Turn the inline block's `rules` field into a dropdown
- [ ] Remove `Phase` and `Block` forms altogether? I think in the long run, we want to manage this all inline in the `Experiment` form, so to avoid clutter and confusion, I would argue we can unregister `Phase` and `Block` models from the admin interface.
