### ISSUE TITLE
Allow admin users to duplicate `Experiment` objects from admin interface

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1136]
After #1135, the form to create an experiment will be even longer than prior to the refactor. To simplify creating an experiment which is virtually identical, apart from a questionnaire of playlist, it would be a nice feature to add an action from the dropdown menu in the admin interface, which creates a copy of an existing experiment, in which the slug is automatically modified to, e.g. `{original-slug}-copy`. 

## Requirements

- Add copy/duplicate button to `Experiment` section in admin interface
- Clicking the duplicate button will copy the `Experiment` and give it a:
  - Name: `{original-name} (copy)`
  - Slug: `{original-slug}-copy`
- Additionally, it will copy the related:
  - `Phase`s
  - `Block`s related to the `Phase`s
  - `ThemeConfig` related to `Experiment` & `Block`, along with its `HeaderConfig` & `FooterConfig`
  - `Feedback` related to the `Block`s?
  - `QuestionSeries` related to the `Block`s?
  - `SocialMediaConfig`

**Comment by drikusroor** [comment]
What do you mean by "virtual identical, apart from a questionnaire of/or playlist"? Does that mean the duplicate Experiment will have no playlist? Or will the playlist be duplicated as well? Perhaps it would be good to have a list of properties / fields that will or will not be duplicated along with the Experiment.

**Comment by BeritJanssen** [comment]
These are choices I have not thought about enough. In general, I think the only reason to duplicate an experiment *without* modifying the questions or playlists would be to add a different Consent form (e.g., you relaunch the experiment but with different contact persons), so perhaps we could even choose to copy everything but the Consent form.
