### ISSUE TITLE
Backend: Rename Experiment to Block

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1147]
- [ ] move code
  - [ ] create migration file
  - [ ] add data migration (including backwards migration)
  - [ ] create `views.py` and `urls.py`

**Comment by BeritJanssen** [comment]
Update: after some discussion, we decided that it might be cleaner and easier to keep the `Block` model within the `Experiment` app, as it cannot exist outside an enclosing phase and experiment.

Still, it might be worth while to move the "rules" and the "actions" subdirectories of "experiment" to their own folder. In the Django sense, this is strange, as folders indicate "apps", but these directories really stand outside of the Django logic a bit, as the classes of the rules files and actions don't represent Django models in themselves.
