### ISSUE TITLE
Score on trophy page is incorrect in TuneTwins

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#1163]
### Description

The final scoring trophy for TuneTwins does not seem to take into account the 100 bonus points awarded at the start of the game. After completing a board with a final score of 150, the trophy page told me that I had only earned 50 points.

### Screenshots

<img width="1084" alt="image" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/1194840/f542a901-ba98-4bd9-91fb-ba9af48b42f7">

### Reproduction steps

```bash
1. Go to TuneTwins.
2. Complete a board.
3. Note your score as you clear your final pair.
4. Compare that score with the trophy page that follows.
```

### Browsers

Safari

### OS

Mac

**Comment by BeritJanssen** [comment]
Fixed - the experiment's bonus points hadn't been set yet in the admin. The frontend component has its own hardcoded total score of 100, which is not great. Will make a separate issue to set this from the total score configured through the admin interface instead.
