### ISSUE TITLE
#ToontjeHoger lead tekst veranderd?

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/MUSCLE#1244]
Lead tekst van ToontjeHogeris die van ToontjeHogerKids? Graag terugzetten in "Hoe snel herken jij een liedje? Heb je gevoel voor ritme en timing? Hoe goed is jouw absoluut gehoor? Doe de minigames op ToontjeHoger en ontdek meer over je eigen muzikaliteit én wat de wetenschap daarover weet."`

![9585F471-8375-451A-8DBE-80AC153C7108_1_201_a](https://github.com/user-attachments/assets/fb58268b-e641-49a5-841a-d4233698aff3)

**Comment by BeritJanssen** [comment]
Adjusted from admin interface.
