### ISSUE TITLE
Improve the handling of missing form elements / questions in `Trial.tsx`

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1245]
In theory, a feedback form could be undefined or an empty array. In case that happens, we now declare it to be an array with an empty object in it. This seems like something that can be improved. TypeScript also doesn't like it. What is the intended behavior in case the feedback form is null/empty? Should we perhaps declare/keep it to be an empty array, or instead declare the empty object to be like a "stub" question with a timeout on it or something?

https://github.com/Amsterdam-Music-Lab/MUSCLE/blob/6734719bda2447748aa25a5ed3c3bcc65a977822/frontend/src/components/Trial/Trial.tsx#L71-L73

**Comment by BeritJanssen** [comment]
It would probably be best to just have the form undefined if `feedback_form` is sent as empty from the backend. It may be that `undefined` throws errors, but I don't think that's not to be overcome. I think the fast answer for why it's currently defined like this is to make sure that in case methods try to do apply some array methods to the `form` object, we don't get hard fails. But from the typing perspective, there's probably less confusing ways to catch & avoid methods which don't make sense without a form array.

**Comment by drikusroor** [comment]
> It would probably be best to just have the form undefined if `feedback_form` is sent as empty from the backend. It may be that `undefined` throws errors, but I don't think that's not to be overcome. I think the fast answer for why it's currently defined like this is to make sure that in case methods try to do apply some array methods to the `form` object, we don't get hard fails. But from the typing perspective, there's probably less confusing ways to catch & avoid methods which don't make sense without a form array.

Ah okay. So what do you think would be better in case of an absent feedback form: "Stop" the experiment and set an error, or silently make it go to the next phase? I would prefer the first option as the second option might cause missing data to be noticed only during the analysis process by the researcher. Or not?
