### ISSUE TITLE
Toontjehoger: fout in stimuli tempo / timing mini game?

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/MUSCLE#1252]
Ik krijg via sociale media het volgende foutmelding

_“ Schokkend vind ik intussen wel dat met grote stelligheid beweerd wordt dat Arrau de Träumerei van Schumann "in het juiste tempo" speelt. Het "verkeerde" tempo is nota bene Horowitz. Niet erg wetenschappelijk!”_

Ik cc het issue ook aan @Atser, die de naamgeving wellicht kan checken.

**Comment by BeritJanssen** [comment]
The stimuli and behaviour have been checked. It's probably a misunderstanding on part of the user that they think a specific performance would be labeled as having the "correct" or "incorrect" tempo.

**Comment by hhoning** [comment]
Atser had in detail naar de playlist gekeken, en kon inderdaad geen fout vinden. Ik heb toen een 'strenge' response op Facebook geschreven. Het blijft belangrijk om bij publiek opereren, ook publiek te reageren. Dank voor het checken van e.e.a. Het had zomaar een fout van ons kunnen zijn.

![image](https://github.com/user-attachments/assets/31e0db08-b593-4f51-aa95-a3b12633c44a)
