### ISSUE TITLE
Make the social media message translateable by moving the content property to `ExperimentTranslatedContent`

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1270]
See also: https://github.com/Amsterdam-Music-Lab/MUSCLE/issues/1204#issuecomment-2270777135

I have already started this ticket, but I have some things that need to be discussed:
- Should a user be allowed to use _points_, _experiment_name_ and potential other placeholders in the message?
- Should the social media message always be passed in the `get_experiment` endpoint and/or should we ideally be able to use it in some `get_next_round` endpoint with a `Final` action too?
  - How do we deal with the placeholder values then and their potential non-existence (like no points available)?

## Proposed requirements

- Modify individual social media configurations in 4 rules files to get its message from the experiment level
- In the rules base class, get the experiment level's social media message 
- Create a simple but elegant way for handling placeholders, including handling singular and plural words like point & points

**Comment by BeritJanssen** [comment]
I was actually a bit stumped on the issue of placeholders. Django's translation mechanism deals with the placeholders elegantly, and I think it would be quite difficult to achieve this through the database. Possible solutions I can think of now:
- implement the `social_media_message` & translation in the codebase, perhaps with a couple of options the user can choose from
- let the user upload a .html file which allows placeholders. That would mean we can use the Django translation backend, as the engine also scans the upload folder
