### ISSUE TITLE
Alignment issues on Safari

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1271]
I think we had this reported before, but it remains an issue: the different circles don't align on Safari.
![image](https://github.com/user-attachments/assets/7265a6cf-1499-4213-a627-d226b0270d90)

See, e.g., http://localhost:3000/block/thk_3 for the Score, and https://tst.amsterdammusiclab.nl/block/thk_mozart for the Autoplay component.

**Comment by BeritJanssen** [comment]
It seems that this issue does not occur anymore in the current develop version.

**Comment by drikusroor** [comment]
#1281 did not fix it. It moved the circle up to invisible areas 😠 Will try another fix

**Comment by BeritJanssen** [comment]
Nope.... (acc after deploy)
<img width="273" alt="Screenshot 2024-09-27 at 15 55 55" src="https://github.com/user-attachments/assets/a2f7f1f7-cd84-4686-9276-da378c0c6176">

**Comment by drikusroor** [comment]
> Nope.... (acc after deploy) <img alt="Screenshot 2024-09-27 at 15 55 55" width="273" src="https://private-user-images.githubusercontent.com/11174072/371560225-a2f7f1f7-cd84-4686-9276-da378c0c6176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTc2NzEsIm5iZiI6MTcyNzQ1NzM3MSwicGF0aCI6Ii8xMTE3NDA3Mi8zNzE1NjAyMjUtYTJmN2YxZjctY2Q4NC00Njg2LTkyNzYtZGEzNzhjMGM2MTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE3MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYWFkMzdmNWUzNGU4YTJiNDNmOTJlNGMwNzhmZTlkZTg2NjQzMDNlZDJhOWEzMjg0NjNkMzVjMzUyMjMyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.if1kc3O7OHFItHm1VW1gJSaHlY7LregO7gmMO_rZ2ko">

But now it is fixed! I think... per #1291
