### ISSUE TITLE
Redirect old /collection urls to new url

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1276]
**Is your feature request related to a problem? Please describe.**
As we don't use `/collection/{collectionSlug}` anymore but instead use `/{experimentSlug` (which used to be called collection), but we are still using link/qr codes that point to `/collection/...`, these incoming users will probably receive an error and cannot reach the experiment (fma collection) they are looking for.

**Describe the solution you'd like**
We add an nginx redirect rule to our nginx configuration that redirects users from `/collection/{slug}` to `/{slug}`.

**Comment by BeritJanssen** [comment]
After next release.

**Comment by drikusroor** [comment]
> After next release.

I can work on this already but we can just merge it to `develop` and it'll get released with the big release automatically 👌
