### ISSUE TITLE
Improve resilience of song duration configuration

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1294]
**Is your feature request related to a problem? Please describe.**
Currently, in Toontje Hoger Kids's [Mozart Block](https://app.amsterdammusiclab.nl/thk_mozart), there are two audio fragments played to the user. The fragments are around 12 seconds long each. In the playlist, however, they are configured as having a duration of 26 seconds. The result is that the `Circle`'s countdown text and animation are cut short at around 13/14 seconds left on the countdown text and the animation being half way.

**Describe the solution you'd like**
The ideal behaviors are probably the following:
1. An audio fragment gets configured to play fully, and
2. An audio fragment is deliberately cut short (e.g. total duration is 60 seconds but we play only a section of 5 seconds of it)

Right now, the feature is error prone in that it allows you to configure a duration that is longer than the actual duration, which then results in a glitchy frontend experience. To make life easier and to decrease the chance of making mistakes, I propose the following features:

1. Whenever the admin user omits a song duration or configures 0 as duration, the backend will pass the actual song duration to the frontend.
2. Whenever the admin user configures a song duration that is _longer_ than the actual song duration, the backend will pass the actual song duration to the frontend.
3. Using our playlist warning system that is already in place, the dashboard will warn the users about configured durations that are longer than the actual song duration, giving the admin user the chance to update is accordingly.

## Update

Apparently it's not _that_ easy to just get the duration from an audio file and it is recommended to install the `mutagen` library. The question is if this new feature is worth installing yet another library...

**Comment by BeritJanssen** [comment]
Isn't the (already installed) `audioread` library enough?
