### ISSUE TITLE
🐛 [BUG] - Result export functions not showing in the admin interface

### ISSUE THREAD

**Issue by Evert-R** [Amsterdam-Music-Lab/MUSCLE#1311]
### Description

Since we now have one big form for an experiment, in which we also create and remove blocks, we're no longer showing the link in the admin interface to the general block list, which contains the export functions.   

Solution:
Bring back the block list, but in a way that it doesn't confuse the end users.

Related to #1318

**Comment by BeritJanssen** [comment]
The `BlockAdmin` is now back, so we can export again.
