### ISSUE TITLE
Progress bar in title

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1334]
**Is your feature request related to a problem? Please describe.**
Instead of showing how many questions, blocks etc. have been already completed numerically (e.g., 1 / 7), include a progress bar in the title of the page.

**Comment by drikusroor** [comment]
For a specific experiment, or for all experiments? And with regards to the technical implementation: Modify the `next_round` to include the current round number and the total number of rounds, or regex the title in the frontend to deduct the progress as a percentage?

**Comment by drikusroor** [comment]
As for the way it should look like, I've been working a bit on a progress bar a bit and came up with this:

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/52e67784-79b7-4756-8995-ca1fd9d77a65">

Do you think something like this would work or should it be more subtle like a little line beneath the title? 🤔

**Comment by BeritJanssen** [comment]
@Lia-JX-Li what do you think?

**Comment by Lia-JX-Li** [comment]
I like this! Is the color, the text inside, and the position of the progress bar be customized later?

**Comment by BeritJanssen** [comment]
The color and text can be customized, but not the position.
