### ISSUE TITLE
🐛 Social media sharing broken again

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1336]
### Description

It seems that, again, X and Facebook have changed the format of their sharing links, and our current implementation is broken.

### Screenshots

Hopefully following soon... please update this issue.

### Reproduction URL

app.amsterdammusiclab.nl/tunetwins

### Reproduction steps

```bash
1. Finish an experiment with sharing links
2. Click on a sharing button while being logged into the social media in question
```

**Comment by Lia-JX-Li** [comment]
<img width="547" alt="截屏2024-10-29 17 28 21" src="https://github.com/user-attachments/assets/16a9b13f-246c-42f6-9df9-e111b0ff0777">
<img width="610" alt="截屏2024-10-24 11 42 46" src="https://github.com/user-attachments/assets/b0861cd7-cc23-418c-88d0-2fd95247d360">
The corresponding sharing interface is shown here. The sharing link is still in there, but it seems not showing the score and other content. Also in X the link is doubled.

**Comment by drikusroor** [comment]
I think it would also be a good idea if we would eventually refrain from using `next-share`, which is still in version `0.27` and hasn't been updated for a year. I briefly looked and `react-share` seems to be maintained regularly and supports many social media https://github.com/nygardk/react-share

**Comment by BeritJanssen** [comment]
That's a really nice find! I was also thinking that it's madness to "roll your own" on this one since we may not have the capacity to maintain this in the future. I do wonder though, looking at the documentation, whether it will be possible to preset the share message for Facebook (this seems to only allow specification of `hashtag`?).

**Comment by drikusroor** [comment]
Tested this on https://acc.amsterdammusiclab.nl/tunetwins and saw that it works as expected for Twitter at least. Facebook does now allow text anymore, see also https://github.com/nygardk/react-share/issues/537#issuecomment-2134104455
