### ISSUE TITLE
Tutorial mode in MatchingPairs

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1338]
**Is your feature request related to a problem? Please describe.**
The TuneTwins team decided that the best way to introduce new participants to the MatchingPairs game would be to give feedback during the first game board in the form of overlays.

**Describe the solution you'd like**
We could pass along a `tutorial` dict from the backend along those lines:
```python
tutorial = {
  "no_match": "This was not a match, so you get 0 points. Please try again to see if you can find a matching pair.",
  "lucky_match": "You got a matching pair, but you didn't hear both cards before. This is considered a lucky match. You get 10 points.",
  ...
}
```

When the frontend displays the score, it also checks whether a message for the key for the given condition is in the tutorial dict. If so, it pops it and displays the message in an overlay

If we go this route, styling the overlay will also need attention. I.e., contrast to the background? Grey out background? Perhaps the `Feedback` component's styling could be partly reused?

**Describe alternatives you've considered**
No alternatives come to mind just yet, should discuss with the team. Ideally, we would arrive at a solution which may also get reused in other experiments, and is not purely engineered against MatchingPairs.

**Additional context**

**Comment by drikusroor** [comment]
Like this? https://react-joyride.com/ or something custom?

**Comment by BeritJanssen** [comment]
That looks actually kind of cool! Let's discuss options on Tuesday.

**Comment by drikusroor** [comment]
Work in progress:

https://github.com/user-attachments/assets/4a6341d6-a170-4f82-826e-23bba64c91b8

These overlays get shown whenever the matching pairs action is configured with a tutorial object:

```py
tutorial = {
        "no_match": _(
            "This was not a match, so you get 0 points. Please try again to see if you can find a matching pair."
        ),
        "lucky_match": _(
            "You got a matching pair, but you didn't hear both cards before. This is considered a lucky match. You get 10 points."
        ),
        "memory_match": _("You got a matching pair. You get 20 points."),
        "misremembered": _(
            "You thought you found a matching pair, but you didn't. This is considered a misremembered pair. You lose 10 points."
        ),
    }

playback = MatchingPairs(
            sections=player_sections,
            stop_audio_after=5,
            show_animation=self.show_animation,
            score_feedback_display=self.score_feedback_display,
            tutorial=self.tutorial,
        )
```

**Comment by drikusroor** [comment]
New version after meeting with Lia yesterday currently looks as follows:


https://github.com/user-attachments/assets/8a9eac50-849d-47b1-bf47-fcd3be5b1cfd
