### ISSUE TITLE
Goldsmiths MSI: sum scores

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#135]

**Comment by jaburgoyne** [comment]
We had discussed generalising this to an improved scoring model, whereby a participant's score data could include multiple running scores (e.g., Gold-MSI scores, the usual task-based scores we currently have, etc.).

**Comment by albertas-jn** [comment]
@jaburgoyne @BeritJanssen 
Could you describe what exactly needs to be done here?

**Comment by albertas-jn** [comment]
@jaburgoyne  Do these scores have to be presented during the experiment, or is it sufficient to have them saved with other results in the database at the end of the experiment?

**Comment by jaburgoyne** [comment]
For now, it's fine just to store them in the database: researchers should be able to choose on an experiment basis whether they want to show any of these
