### ISSUE TITLE
🐛 [BUG] - ONE PAIR BEING SILENT on original board of Matching Pairs Congo version 

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#1368]
### Description

Dear MUSCLE Team,

After successfully collecting data in the jungle using Toughbook, we are now planning to conduct the same experiment with Dutch children. In preparation, I am filing this issue for your attention. Thank you in advance for looking into it!

Bug Description:
It seems that the issue arises specifically when loading the original board. One of the eight pairs does not play any sound. Interestingly, this problem does not occur with every board and is mostly resolved by reloading and generating a new board.

Let me know if you need any additional details or steps to reproduce the issue.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by BeritJanssen** [comment]
Seems to me like one of the files cannot be found. Can you send the playlist csv and files?

**Comment by Lia-JX-Li** [comment]
I will attach it tomorrow morning when I'm in office and have the toughbook at hand!

**Comment by Lia-JX-Li** [comment]
[original.csv](https://github.com/user-attachments/files/17812592/original.csv)
