### ISSUE TITLE
🐛 About page not showing

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1371]
### Description

The About page is currently not showing the content set in through the admin interface.

### Screenshots
<img width="571" alt="Screenshot 2024-11-15 at 14 40 32" src="https://github.com/user-attachments/assets/f8649bf5-d74b-4185-af54-cc6782e8bf0f">

### Reproduction URL

https://tst.amsterdammusiclab.nl/thkids/about

### Reproduction steps

```bash
This page definitely has an about page configured, but it isn't showing. Perhaps the transition to using the translated version of the text is not quite working yet (haven't been able to look into this locally yet).
```

**Comment by drikusroor** [comment]
![image](https://github.com/user-attachments/assets/c11fce35-f343-4f5e-9a26-43c55824d93d)

Seems to work for me on https://tst.amsterdammusiclab.nl/thkids/about 🤔

**Comment by BeritJanssen** [comment]
I figured it out! It's caused by returning with a session that was still active. Since the participant had finished sessions, this would lead to the session cookie being set to a lower number than the number of finished sessions. It's a bit of an edge case, but I pushed a fix so we don't run into this after release on acc / prod.
