### ISSUE TITLE
🐛 Countdown in Autoplay not centered anymore

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1379]
### Description

See here:
https://amsterdam-music-lab.github.io/MUSCLE/storybook/?path=/story/components-autoplay--default

Perhaps this happened as a side effect of the recent histogram PRs?

### Reproduction URL

[https://tst.amsterdammusiclab.nl/block/huang_2022](https://tst.amsterdammusiclab.nl/block/huang_2022)

### Reproduction steps

```bash
1. Start any experiment with Autoplay actions. NB: this seems to be specifically a problem with experiments with external audio, which means we don't use web audio.
```

**Comment by drikusroor** [comment]
This has been fixed per #1393
