### ISSUE TITLE
🐛 [BUG] - The playlist select input appears in a weird (top-left of page) position for blocks on a new experiment

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#1417]
### Description

My first hunch is that its container needs a `position: relative` so that the absolute position of the input works correctly. But it might also be a `django_select2` issue.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by BeritJanssen** [comment]
Btw, the select widget also doesn't have a proper dark mode: while the background of the select element stays white, the font becomes lighter, which makes it unreadable.
