### ISSUE TITLE
sqlite to Postgres

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#221]
The development environment now still uses sqlite. This has the advantage of sharing databases easily, but means that some database logic which works on sqlite fails on Postgres - which defeats the purpose of Dockerizing somewhat.

Steps to remedy:
- change the development settings
- use database dump (see, e.g., [documentation here](https://www.coderedcorp.com/blog/how-to-dump-your-django-database-and-load-it-into-/) to transfer data
- document this in the Readme

**Comment by drikusroor** [comment]
I don't see a sqlite in this project (anymore?) and I use `docker-compose.yml` for development, which uses a postgresql db. Can I assume this issue can be closed?
