### ISSUE TITLE
Add Feedback button

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/MUSCLE#264]
Add feedback button with 2/3 questions and text field - comparable to the feedback link on  all UvA sites. Could be a generic feature for all AML experiments?
![uva](https://user-images.githubusercontent.com/72495504/195585010-be2884c6-5395-4892-b258-200e842066c3.jpg)

**Comment by drikusroor** [comment]
Do we still want this and are we talking about something as easy as adding a script tag in `index.html` or will it require some more work?
