### ISSUE TITLE
Amsterdam Music lab: scaling of widgets error?

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/MUSCLE#282]
In ToontjeHoger some widgets (see below) scale erroneously with a browsers  page scaling (Command+ and Command-). 
![Scaling webpage error (down-scaled)](https://user-images.githubusercontent.com/72495504/203063194-a6e43d6b-733d-4570-8eb0-51a07378f166.jpg)
![Scaling webpage error (up-scaled)](https://user-images.githubusercontent.com/72495504/203063198-e23ee4f5-7552-4c00-8479-0397fe544f45.jpg)

**Comment by BeritJanssen** [comment]
Fixed per #1291
