### ISSUE TITLE
Migrate Hooked experiments

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#312]
- [x] move audio data to acceptance & new production server
- [x] create valid csv files / sections for the playlists
- [x] change all references in the Amsterdam Music Lab blogs (ideally, write a utility function for this, see [corresponding website issue](https://github.com/Amsterdam-Music-Lab/amsterdam-music-lab/issues/7))
- [x] download existing json data from illcaml server
- [x] take down the gunicorn process on illcaml server

**Comment by albertas-jn** [comment]
@jaburgoyne Eurovision and Kuiper experiments are now on ACC and APP with slugs `eurovision_2021` and `christmas_2020`. Shall I now update the links in the blogs?

**Comment by albertas-jn** [comment]
The links on the website have been updated. It's actually very easy to do this by changing the URL once or twice for an experiment. I don't think there's a need to write a utility function for that.

**Comment by albertas-jn** [comment]
@BeritJanssen Can you do the last two tasks in the list?
