### ISSUE TITLE
Automated functional tests

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#41]
The Docker containers running the app sometimes stop running - automated functional tests would help to detect this. (And a mechanism to start everything up again automatically.)

[Karma](https://www.testim.io/blog/karma-js-testing-what-why-and-how-to-get-going-right-now/) can be used for this: it simulates running the code in a browser. A very simple test would be just to see if, e.g., a `title` is present if you call `app.amsterdammusiclab.nl` (or whatever url you run the application on). Anything that wouldn't work if the backend server is down.

Or is Selenium the go-to-choice?

Major browsers:
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge
And mobile device support.

**Comment by albertas-jn** [comment]
@BeritJanssen What is the status of this issue?
At the moment, we have selenium tests for BeatAlignment, Eurovision and Categorization.
