### ISSUE TITLE
Rescore results

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#425]
We have a `scoring_rule` CharField tied to each `Result` object. We should offer users a way to
- get a set of `Result` objects (e.g., by `question_key`)
- change the scoring rule for all these objects
- trigger rescoring

**Comment by jaburgoyne** [comment]
I just saw @albertas-jn's message on Teams. I think I would recommend closing this issue for now. Over-writing scoring after an experiment has taken place is dangerous indeed.

Instead, less focus our energy on the generalised version of https://github.com/Amsterdam-Music-Lab/MUSCLE/issues/135 for now, and *maybe* think a little more about the user interface for assigning scoring rules at the beginning of the experiment.

Our ultimate goal here is to encourage users to think carefully about their scoring rules and to make them easy to work with. That means it should be easy to set up a scoring rule at the beginning of the experiment (at the same time as question selection) and easy to pull out the results of different (sub-) scores from the admin (and Python) interface (https://github.com/Amsterdam-Music-Lab/MUSCLE/issues/135). 

Perhaps we should make a new issue or rename this one to take into account how to define scoring rules from within the admin interface?
