### ISSUE TITLE
amsterdammusiclab.nl does not resolve automatically on all devices

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#511]
I thought this had been fixed, as it works for me now, but some users are reporting that amsterdammusiclab.nl does not resolve automatically to www.amsterdammusiclab.nl. I am filing the issue here because we could also consider app.amsterdammusiclab.nl as an alternative.

**Comment by drikusroor** [comment]
I closed this issue as it is not related to the MUSCLE project and the issue already exists here: https://github.com/Amsterdam-Music-Lab/amsterdam-music-lab/issues/11
