### ISSUE TITLE
Fix Selenium setup (documentation)

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#548]
Right now, after setting up Selenium and the `.ini` file as described in the test file, I get the error
```
Traceback (most recent call last):
  File "tests-selenium.py", line 65, in setUp
    raise Exception("Unknown browser")
Exception: Unknown browser
```

**Comment by albertas-jn** [comment]
@BeritJanssen  Could you please post the contents of your `tests-selenium.ini` file?

**Comment by BeritJanssen** [comment]
```
[selenium]
    browser=Chrome  # Firefox | Chrome | Safari | Edge
    headless=no      # yes | no  (headless does not work on Safari)
[url]
    root=http://localhost:3000
[experiment_slugs]
    beat_alignment=bat
    eurovision=eurovision_2020
```

Obviously, I already tried different browsers, lowercase / uppercase, but no luck yet.

**Comment by albertas-jn** [comment]
The solution is to remove the "comments" (#...). Comments work differently in .ini files.
