### ISSUE TITLE
Music Preferecences:  Social Media Share Text 

### ISSUE THREAD

**Issue by XHuang218** [Amsterdam-Music-Lab/MUSCLE#581]
The current text for sharing on social media is showing points award , it does not really fit the context of Music Preferences Experiment. It would be nice to present a more informative summary that highlights participants' actions in the experiment. So, the text provides a clear and concise summary of the information to be shared on social media.

Proposed Text:
Your top 3 favorite songs: 'XX,' 'YY,' 'ZZ.' You know N'out of 64 songs. All players' top 3 songs: 'A,' 'B,' 'C.'

In Chinese:
您最喜欢的三首歌曲：'XX,' 'YY,' 'ZZ‘；您知道64首歌曲中的N首；其他人最喜爱的三首歌曲：'A,' 'B,' 'C'。

**Comment by BeritJanssen** [comment]
Considering that people will share this, wouldn't it be better to have this read "My top 3 favorite songs: ..." It would also be good to include the URL, to invite other people to play, too. So start with "I rated songs on {{url}}! My top 3 favorite songs..." @XHuang218 what do you think?

**Comment by XHuang218** [comment]
Yes, it'd be better to have the text read "My top 3 favorite songs ..." and it makes sense to include the URL. 
But I want the text to be direct to the point at the beginning, so it would have this read "Explored musical preferences together at {{url}}! My top 3 favorites songs: 'XX,' 'YY,' 'ZZ.'；I know N out of 64 songs；All players' top 3 songs: 'A,' 'B,' 'C.'

In this case, the new Chinese translation is:
一起探索音乐喜好!{{url}}  我最喜欢的三首歌曲：'XX,' 'YY,' 'ZZ‘；我知道64首歌曲中的N首；其他人最喜爱的三首歌曲：'A,' 'B,' 'C'。

**Comment by BeritJanssen** [comment]
This has already been addressed, closing.
