### ISSUE TITLE
Music Preferences: Chinese Title Text 

### ISSUE THREAD

**Issue by XHuang218** [Amsterdam-Music-Lab/MUSCLE#582]
![截屏2023-10-12 21 01 43](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/94059223/94ff8fca-6385-4f15-9135-0d7aeccc4a52)

The title text now is incorrect, the order of the characters should be adjusted. The order in the previous version was correct ( issue #559). **The correct text is:**

**解锁乐之爱**          (corresponds to    Love Unlocked) 
**解锁乐之识**          (corresponds to   Knowledge Unlocked )
**解锁乐之友**          (corresponds to   Connection Unlocked)

For helping understand the text， 
爱 corresponds to 'Love'
识 corresponds to 'Knowledge'
友 corresponds to 'Connection'

In Chinese, these nouns are typically positioned at the end."

**Comment by BeritJanssen** [comment]
This was caused by changing the English text around - so unforunately, the translation will be swapped, too. Will have to work around this in a different way.
