### ISSUE TITLE
Music Preferences: Chinese Text for the Progress of Songs Played

### ISSUE THREAD

**Issue by XHuang218** [Amsterdam-Music-Lab/MUSCLE#583]
'Song 4 OUT OF 8'   in a concise manner in Chinese is ' 4/8首歌' .

There are 64 songs in total, and the text will be N/64首歌。
![7981697138836_ pic](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/94059223/69f5a235-0632-4a2d-b2b9-84c4ace8f490)

**Comment by BeritJanssen** [comment]
Note for later: formatted strings should have the format `_('Some text with a %(variable)') % {'variable': some_variable}`, i.e., the fomatting dict should be placed outside of the `gettext` wrapper. Otherwise translation won't work.
