### ISSUE TITLE
Music Preferences: Consent form

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#588]
Add consent form and Chinese translation.

**Comment by XHuang218** [comment]
Just update the consent form  by specifying minimum participant age (16 years old) required by Ethics Review. The updated form is in Teams: https://amsuni.sharepoint.com/:w:/r/sites/FGW_RES_AIHR_ILLC_Amsterdam_Music_Lab/Gedeelde%20documenten/Music%20Preferences/FGw%20consent%20form/General%20Combined%20information%20brochure%20and%20informed%20consent.docx?d=wdb85d1f44a204c57891b839aa872a4c9&csf=1&web=1&e=YAKusz
