### ISSUE TITLE
Section upload fixes

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#590]
The section upload still doesn't quite behave as desired. Needed fixes:
- add comment on how filenames will be processed (`/` will be removed)
- show allowed file extensions
- prevent upload if the file type is not allowed

**Comment by Evert-R** [comment]
@BeritJanssen Where should this go? 
**add comment on how filenames will be processed (/ will be removed)**
(The upload via the admin doesn't do this. It only selects a file, so there never will be a `/` in the filename)
