### ISSUE TITLE
Create Simple Consent Module for Congo Field Experiments

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#600]
Create module that can be used to collect consent data for Congo Field Experiments. 

Module should be able to allow experimenter to give unique string ID along with attached media (TBD). This may be either uploaded audio (declaring consent), fingerprint image file, or just click screen to say yes. (Will update when know after Nov 16th)

**Comment by BeritJanssen** [comment]
NB, we discussed the option to collect consent on paper, rather than in the app. In the interest of time, any of the options that don't involve clicking (i.e., the now implemneted solution) should be done offline IMO.

**Comment by davidjohnbaker1** [comment]
Closing issue here, as this will be taken care of not on AML framework
