### ISSUE TITLE
Create demographic module for Congo Field Experiment

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#601]
Create module that will allow scientist to enter unique ID, then be taken to page that will have text fields for:

* Age 
* Location
* Time of Data collection
* General Notes (large field) 

Will update with specific modules post Nov 16th meeting.

**Comment by BeritJanssen** [comment]
This should be relatively easy to implement.

**Comment by davidjohnbaker1** [comment]
Closing this issue, taken care of with pre-existing database via collaborator
