### ISSUE TITLE
Create Field Branch of Tune Twins 

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#603]
Create a new branch of the TuneTwins game that will be the software used during the Congo Field Data collection. Separate issues will be filed for this, but it is so that we can create a more pared down version of the game that an experimenter will manipulate with minimal instructions, less animations, and removed feedback. This branch will also be what is used to load the software on the computer taken to Congo.

**Comment by BeritJanssen** [comment]
@davidjohnbaker1 , let's try to uphold the [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) paradigm, i.e., we implement features but make sure they are *compatible with the remaining code base*. Parallel branches will mean that a given part may grow stale, essentially losing all the work invested in it which may be meaningful for other research (e.g., #606). We can make a new *rules file* for the field work, and let the backend send instructions to the frontend on whether or not animations should be shown. The other "minimalizing" to be done can already be done within the existing code base.

**Comment by davidjohnbaker1** [comment]
That works for me!
