### ISSUE TITLE
Create Control Dashboard for Congo Tune Twins

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#606]
When launching the Congo branch, a dashboard similar to https://toontjehoger.amsterdammusiclab.nl/toontjehoger should be the first screen the scientist sees. 

She should then have the choice to select entering data for 

~~1. Consent~~ -> done offline
~~2. Demographic Data~~ -> done offline
1. Visual example
2. Original Tune Twins
3. Spectral Tune Twins
4. Timing Tune Twins
5. Pitch Tune Twins

Selecting each choice takes the experimenter through one iteration of the game, then returns to the home screen.

**Comment by BeritJanssen** [comment]
This essentially ties in with #259 : `experiment_series` should be redesigned so it can be used for a dashboard-type of environment.
