### ISSUE TITLE
Create Analysis Dashboard for Congo Branch

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#607]
After launching the Congo Branch of tune twins, the scientist should be able to see the current status of the data that has been collected. This should include:

* Number of participants successfully entered for each condition in #606 as summary table
* Confirmation the JSON file format is correct

**Comment by BeritJanssen** [comment]
Nice to have! I envision that we can do this from the admin interface.
