### ISSUE TITLE
Create Six Card Tutorial for TuneTwins Congo Branch

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#609]
Create module of TuneTwins where scientist is able to select running a tutorial, then a pared down version of TuneTwins (#605) plays with only 6 cards. This is done to give people practice before moving on to the 16 board.

**Comment by BeritJanssen** [comment]
The number of pairs can easily be adjusted. At the moment, this would have to happen through a separate rules file, though we may also consider whether to use the `number of rounds` setting in the admin interface as `number of pairs`. Might be confusing for future maintenance though.

**Comment by BeritJanssen** [comment]
@davidjohnbaker1 , I believe this was off the table? I'll close the issue, feel free to reopen if you decide this is needed after all.

**Comment by davidjohnbaker1** [comment]
Yes, this can be closed.
