### ISSUE TITLE
Load error?

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/MUSCLE#624]
https://amsterdammusiclab.nl doesn’t load, but https://www.amsterdammusiclab.nl does.

N.B. Might have reported this earlier as well.

**Comment by drikusroor** [comment]
`www.amsterdammusiclab.nl` seems to have an `A` record that points to an IP owned by the UvA and a `CNAME` that points to ` illc-aml.science.uva.nl.`: [DNS Checker <www.amsterdammusiclab.nl>](https://dnschecker.org/all-dns-records-of-domain.php?query=www.amsterdammusiclab.nl&rtype=ALL&dns=google)

However, `amsterdammusiclab.nl` does not seem to have these records but instead have a `NS` record (that eventually also points to an IP owned by UvA): [DNS Checker <amsterdammusiclab.nl>](https://dnschecker.org/all-dns-records-of-domain.php?query=amsterdammusiclab.nl&rtype=ALL&dns=google).

So probably it's just configuring the DNS correctly to fix this inconsistent behavior.

**Comment by BeritJanssen** [comment]
We'll switch to a new server before long, where we can correct the behaviour. NB this is an issue for the amsterdam-music-lab repo (relating to the blog), so I moved the issue there: https://github.com/Amsterdam-Music-Lab/amsterdam-music-lab/issues/11
