### ISSUE TITLE
Visual Introduction Example for Teaching Tune Twins for Congo

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#625]
We like to have a classic (visual) version of Memory that we can use as instruction (cq. Familiarization phase of the experiment): a visual version of TuneTwins that, instead of playing an audio file and showing the equalizer, will show an image. We would like to be able to upload a set of 8 image files, which then form the pool that populates the 4x4 grid. Overall, we are interested in matching the analogue/card version of the game as closely as possible. This also means that there will be no audio feedback based on a player's interactions with the board.

**Comment by BeritJanssen** [comment]
How high is the priority of this issue? MUSCLE is not inherently designed for image content, so quite some changes would be required to achieve this. I understand that the transfer from the physical game to the screen is something you would like to show here, but is this *essential*?

**Comment by davidjohnbaker1** [comment]
In our meeting last week, we decided this is quite a high priority item for us. It is essential that we have it by April, since it needs to be a part of the Congo battery. 

If possible, we would like a working version of this by the end of January, so that it can be a part of our dry-run practice in February when we play this with children. Is this too large of an issue to request by then?

**Comment by davidjohnbaker1** [comment]
Regarding the two comments on the #687 code so we can close this:

1. Can you use the #605 feature on the visual condition branch so there is no visual feedback on the visual condition here as the default?
2. Can you swap out Ringo and company with the attached images here of animals? 

(Can DM them as well, not sure how they are uploaded here)  

![BlueDuiker](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/a4002ae5-6263-4b7d-b9c4-d46c8c9c4788)
![Chimpanzee](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/acd46ba6-e1c3-47ad-b20f-35b5a3a338dc)
![Elephant](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/d6f7bb96-a37b-49a2-b1eb-7b7a8654b0b7)
![Pangolin](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/75f528c1-42e0-410b-b03b-4a73e0acad9c)
![Panther](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/f4681bd5-f9ab-407b-b193-79b25e2a4056)
![RedRiverHog](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/4cec4856-f52a-4235-9142-e4c45cbf4550)
![Tilapia](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/e8b9e75c-c5dd-4236-96d4-fb04cd006c21)
![Turtle](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/05811301-8600-49bb-8e24-8a2ac6fe274f)

**Comment by drikusroor** [comment]
A first version of the tunetwins/matching pairs visual introduction (with the animal images) can be seen here: https://acc.amsterdammusiclab.nl/tunetwinsvisual

**Comment by davidjohnbaker1** [comment]
This looks great to me. If it's possible to integrate the other requests such as the "no animation, no extra, no instructions" as the default version of this, that would also be quite helpful. If you're prefer to keep that separate, then I think this can be closed and mark as resolved?
