### ISSUE TITLE
Update Wiki or README.md with troubleshooting steps

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#630]
Apparently, in #628 a tab was muted. I've googled around a bit and there are no JavaScript APIs that allow us to check whether the tab is muted from within the app. What we could do, however, is add a section to the [Wiki](https://github.com/Amsterdam-Music-Lab/MUSCLE/wiki) or to the [readme](https://github.com/Amsterdam-Music-Lab/MUSCLE/blob/develop/README.md) with a list of troubleshooting steps that allows users or hosts of the experiments to catch the majority of issues straight away. 

On the top of my head I'm thinking of instructions like:
- Is the audio of the device turned on and set at a loud enough volume?
  - If you are using bluetooth audio devices such as headphones/speakers is bluetooth turned on and are the device and the heaphones/speakers connected?
  - If you are using the device's internal speakers, have you made sure the device is _not_ connected to a bluetooth audio device?
- Have you confirmed that the tab is not muted?
- Have you tried refreshing the page?
- Have you tried rebooting the device?

What do you think? Is the phrasing too condecending maybe? We could easily start with a small list based on the reports we actually receive (such as a muted tab in #628). And is the Wiki the best place for this? 

## UPDATE

I have created this wiki page for now: https://github.com/Amsterdam-Music-Lab/MUSCLE/wiki/X.-Troubleshooting

Do you think that's enough for now or does it need more introduction and list items? Also, would it be nice to promote the page with a link/reference in the [README.md](https://github.com/Amsterdam-Music-Lab/MUSCLE) so that it's easier to find when our users actually have issues and want to know what to do?

**Comment by BeritJanssen** [comment]
Nice, thanks for adding this to the WIKI. Indeed, it would be good to place a link in the README. I'm not against adding useful information to the README per se. 😉
