### ISSUE TITLE
Fix CSS for Six Card Tutorial

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#652]
Following merge of #609 , will need to change CSS to have 2x3 grid (2 rows, 3 columns)

**Comment by drikusroor** [comment]
Hi @davidjohnbaker1, does only your own specific experiment (The Six Card tutorial) need a 2x3 grid? I assume it shouldn't cause the already existing Matching Pairs experiment to break, right?
