### ISSUE TITLE
CSV export doesn't export the "question_key" of results

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#670]
I noticed that the key is not exported consistently, while it's probably often quite useful for analysis to know which key a given result belongs to.

**Comment by drikusroor** [comment]
@BeritJanssen on what environment did you encounter this issue and with which experiment?

**Comment by BeritJanssen** [comment]
This happens on the current develop branch for all experiments which have "Trials" in them, as far as I can tell.

To reproduce, go to admin interface (local or acc), go to "Experiments" overview. Click "export csv" next to an experiment, e.g., "Musical Preferences", and download without further adjustments. The downloaded csv has all kinds of fields for a given result, such as `given_response`, `expected_response`, but `question_key` is missing. It doesn't seem to matter which template for download is chosen.
