### ISSUE TITLE
Songs are repeated in the Musical Preferences experiment

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#684]
**Describe the bug**
During the Musical Preferences experiment, the same songs keep coming back within the same session.

**To Reproduce**
1. Go to [https://acc.amsterdammusiclab.nl/mpref](https://acc.amsterdammusiclab.nl/mpref)
2. Do the experiment
3. Pay attention and see if the same song comes back

**Expected behavior**
Only unique songs should be played in one session.

**Screenshots**
https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/8208970/fd5013db-5cce-433b-af7b-ba509e4faa92

**Desktop (please complete the following information):**
n/a. It's a backend problem.

**Smartphone (please complete the following information):**
n/a. It's a backend problem.

**Additional context**
It seems to happen fairly randomly (or I haven't found a pattern at least)

**Comment by XHuang218** [comment]
It seems random to me as well. Do we know the reason for this? Is it feasible to get it fixed by the end of January?
