### ISSUE TITLE
 Move `createSession` request to Experiment component?

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#714]
There is a `StartSession` component whose only responsibility is to fire a request to create a session, and pass it through to its parent (`Experiment`). @jaburgoyne Is there any scenario in which we would want to *not* create a session? It seems silly to explicitly set `StartSession` through the backend in the `first_round`, if we cannot ever proceed to the `next_round` calls, which depend on the session to be created. I would propose to get rid of that component and just fire the `createSession` call from the `Experiment` component. This avoids:
- unnecessary repetition of `StartSession` in all rules files
- the definition of a component without any html (other than error handling, which can be done at a higher level just as well)
- problems with passing through data between `Experiment` and `StartSession`

**Comment by jaburgoyne** [comment]
I also can't see a reason why one would not want to create a session. If you feel that it is more streamlined to eliminate StartSession – I tend to agree – go ahead!
