### ISSUE TITLE
TuneTwins card front broken on develop

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#715]
NB: this is not a problem on the servers, but we will need to fix this prior to our next release. In the latest version, the MatchingPairs component does not display cards correctly:
<img width="648" alt="Screenshot 2024-01-17 at 09 58 28" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/11174072/d49ce9df-5657-4a5f-95d0-2a387c6a31b1">

Expected behaviour: a click on a card should bring up the histogram animation.

I had hoped that this was caused by outdated css, but recompiling didn't solve the issue.

**Comment by drikusroor** [comment]
It seems like a broken image link. Can you see which image it's trying to fetch?
