### ISSUE TITLE
Small Visual Feedback Option

### ISSUE THREAD

**Issue by davidjohnbaker1** [Amsterdam-Music-Lab/MUSCLE#716]
Related to #605 and #609 and #603.

All audio versions of the Congo Branch (#603) should have version where feedback options are shown in small text, in bottom right corner of screen. The purpose of this is so that the player (member of BaYaka group) can play the game without having feedback that is meaningful to them, but the experimenter (@Lia-JX-Li ) can visually confirm that the game is working as expected. 

The final solution will look like the normal version of the game, with the feedback location and size changed. See attached (but smaller text).

![Screenshot 2024-01-17 at 10 21 35](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/10405851/c674074d-6af1-46c3-9d3e-43b2b7e89c31)

**Comment by drikusroor** [comment]
@davidjohnbaker1  Should this new version (feedback smaller, in the bottom-right corner) replace the currently existing version or should it be a configuration option? (see below for example)

```py
playback = MatchingPairs(
    sections=player_sections,
    stop_audio_after=5
    feedback="bottom-right-small" # or something equivalent to this (options: default, bottom-right-small)
)
```

**Comment by drikusroor** [comment]
This is what I'm working on currently. Is it what you had in mind (see small score feedback in bottom right)?

<img width="919" alt="image" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/8208970/2bea9948-4301-4f50-8427-23962174e5f2">

**Comment by davidjohnbaker1** [comment]
Just going to double check this with the team, then will approve. But looks good to me!

**Comment by hhoning** [comment]
parametrization of the game is indeed more elegant than branching :-)

Small text at the bottom looks OK (assuming no scrolling is needed). @davidjohnbaker1
