### ISSUE TITLE
Podman-ify the application so that we automatically deploy to the new (test) server

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#718]
**Is your feature request related to a problem? Please describe.**
Currently, it's tedious to deploy the MUSCLE project. We have to ssh into one of the servers, fetch the latest branch, run docker commands, etc. Ideally, we should have some form of CI/CD with automated deployment, reducing our workload and shortening the feedback cycle for testing.

**Describe the solution you'd like**
There has been a plan to convert our Docker setup to use Podman (which is similar and compatible). Podman then runs on the server, and by using a self-hosted GitHub Action runner we can run the required Podman commands from our Github workflow.

**Requirements**:

* [x] Update (or for now add) workflow to run Podman commands to *build* the Podman images that will eventually run on the new server
* [x] Update the Dockerfiles where needed
* [x] Update (or for now add) workflow to run Podman commands to *run* (and therefore deploy) the Podman containers on the new server
* [x] ~Move the Storybook jobs to its own workflow that still runs on Github's cloud runner?~ Update: it already is separate!
* [x] Change DNS settings so that [tst.amsterdammusiclab.nl](https://tst.amsterdammusiclab.nl) will give us the frontend and `/admin` will give us the Django backend dashboard. *The DNS change has already been requested
* [x] Configure it so that the application will be deployed after pushes to `develop` (or by a manual trigger) to the test environment using the test environment variables configured in Github.
* [ ] Verify that everything works and if not, fix things where necessary.

**Describe alternatives you've considered**
* I think we have talked of just building the frontend in GitHub Actions using a cloud runner with a basic yarn image. But having everything configured in Podman is more consistent, I guess.

**Additional context**
- We can draw inspiration from the AML blog that [has already been podmanified](https://github.com/Amsterdam-Music-Lab/amsterdam-music-lab/pull/18).
- We aren't Podman connaisseurs, so please ask Auke for advice if you are stuck
- See also:
  - #570 
  - #592
  - Work in progress: #722

**Comment by BeritJanssen** [comment]
When discussing with Auke, I thought we had a setup in mind where the images would also be built by the runner on the server.

**Comment by BeritJanssen** [comment]
See also #592 .

**Comment by drikusroor** [comment]
> When discussing with Auke, I thought we had a setup in mind where the images would also be built by the runner on the server.

That's correct and is also what will be happening. Did I describe it incorrectly or ambiguously somewhere?

**Comment by BeritJanssen** [comment]
No, all good! I misread your issue description.
