### ISSUE TITLE
Proposal: Run E2E tests after deployment to the Acceptance (and/or Test) environment

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#746]
## Requirements

- [x] E2E tests are run in a Chrome/Chromium-based browser
- [x] E2E tests are run in headless mode in its CI/CD workflow
- [ ] ~On Production, only smoke tests are run after a deployment to verify the site is still running and experiments can be loaded~ See issue #1060 for the smoke tests on Production after a release
- [x] On Acceptance, the full E2E suite is run after a deployment to verify the most critical features of MUSCLE are still working

## Original proposal

**Is your feature request related to a problem? Please describe.**
Sometimes new features, refactors, and fixes have unintended consequences that might not be captured by frontend and backend unit tests. This might cause is to discover newly introduced bugs later than is necessary.

**Describe the solution you'd like**
It would be nice to at least run some smoke/e2e tests periodically that verify if the MUSCLE platform as a whole is still working like it is supposed to. We already have some selenium tests configured which we can use for now and which we can expand upon over time. We can run these tests after deployment to the Acceptance environment. This means we don't have to configure new environments in our CI/CD pipeline and we can begin testing straight away.

**Describe alternatives you've considered**
I've thought about maybe using Playwright or Cypress, but since we already have Selenium, it might make more sense to just continue using that.

**Additional context**
Running the E2E tests automatically after deployment requires an automated CI/CD pipeline as well. Currently this does not yet exist for Acceptance, but it almost exists for the new Test environment.

**Comment by BeritJanssen** [comment]
As discussed: instead of nightly, perhaps after every build would be sufficient.

**Comment by BeritJanssen** [comment]
Hum, I thought "nightly" would be more frequent than "after push to develop", but you may be right that nightly is actually going to be less frequent. We concluded that it would be most efficient to run the e2e tests against the server itself, so no, the platform wouldn't be run in github actions, but deployed on the server + e2e test triggered to check whether requests to the server give expected responses. The only problem we have for that is a reproducible database - but perhaps we can work around that with Django fixtures (i.e., set up experiments and playlists with json exports from the production server, as is now already done for some Django unit tests). That way we can be sure a calling `experiment/myFancyExperiment` will give a response. Perhaps we would also always want to run tests with a `participant_id=testing` or similar, so as cleanup after e2e tests, we can delete all sessions + results associated with that participant.

**Comment by drikusroor** [comment]
> Hum, I thought "nightly" would be more frequent than "after push to develop"

To be clear, I was talking here about commits to a PR, as part of the existing test suite and thus as part of the checks you do _before_ you merge your branch to `develop`. But if you mean after every commit to `develop` that would mean post-merge, right? That would mean you would only find out about potential bugs after you've already merged. Is that correct? Just asking so that we are on the same page.

**Comment by BeritJanssen** [comment]
Yes, in my view we'd run E2E on the test server after pushes to develop. That would mean we'd indeed still merge buggy code, but catch the bugs prior to releasing them for production. The need to create a running server, which can be accessed from Selenium, seems prohibitive to make this part of the Github test suite. But perhaps there are options to do that?

**Comment by albertas-jn** [comment]
@drikusroor What would be the advantages of Playwright or Cypress over Selenium?

**Comment by drikusroor** [comment]
> [@drikusroor](https://github.com/drikusroor) What would be the advantages of Playwright or Cypress over Selenium?

In my experience, Cypress seems to be easier to use than Selenium. I have used it in the past and it seemed easier to set up and easier to write tests. But I don't have any problems with Selenium per se. With regards to Playwright, I see the name pop up more and more but I've never checked it out or anything. Might be just buzz / hype.

**Comment by drikusroor** [comment]
Implemented in #1010 - except for smoke tests in production, but there's a new ticket for that => #1060
