### ISSUE TITLE
TuneTwins Feedback are placed in the center above the cards instead of on both sides

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#756]
**Describe the bug**
TuneTwins Feedback are placed in the center above the cards
**To Reproduce**
I was using Imac Chorme and also tested on safari with the link https://acc.amsterdammusiclab.nl/tunetwins 

**Expected behavior**
The Feedback "pick a card/misremembered/good job/no match/lucky match" and the feedback "score: [number]" should be line up with both edges of the 4 by 4 grid like it used to. 

**Screenshots**
<img width="661" alt="截屏2024-02-06 17 50 58" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/65351308/5841e866-49ab-46bc-b7af-f9a6fd4c3399">

**Desktop (please complete the following information):**
 - Mac OS
 -  chrome Version 114.0.5735.133 & safari Version 16.1 (18614.2.9.1.12)

**Comment by Lia-JX-Li** [comment]
![MicrosoftTeams-image](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/65351308/756e1d76-8d3f-409f-93d5-8d8c0bb4cc82)
As Henkjan mentioned, the visual version of the game also have the same problem.

**Comment by BeritJanssen** [comment]
@drikusroor , I see that VisualMatchingPairs also uses a different font.
