### ISSUE TITLE
[Eurovision] Countdown to playback jumpy

### ISSUE THREAD

**Issue by albertas-jn** [Amsterdam-Music-Lab/MUSCLE#762]
## Description of the problem

The 3 sec countdown before playing a song goes down, up and down again.

## Expected behaviour

...

## How to reproduce

- Experiment/ruleset: Eurovision experiment, 
- Environment: local develop, acceptance server, 
- Browsers: Firefox, Chromium

**Comment by drikusroor** [comment]
What does this mean?

**Comment by albertas-jn** [comment]
The 3 sec countdown before playing a song goes down, up and down again.

**Comment by albertas-jn** [comment]
Eurovision experiment, local `develop`, acceptance server, Firefox, Chromium

**Comment by BeritJanssen** [comment]
This is occurring again after #1003. Proposed solution: remove the countdown, and instead show the loading spinner with the preload message ("Get ready!")
