### ISSUE TITLE
`scripts/test-back` and `scripts/test-front` do not work anymore

### ISSUE THREAD

**Issue by albertas-jn** [Amsterdam-Music-Lab/MUSCLE#763]
@drikusroor?

**Comment by drikusroor** [comment]
Hey @albertas-jn, I think I need more context. On both my machine and in GitHub on the `develop` branch they seem to work fine. Did you rebase your feature branch onto `develop` and did you rebuild your containers (if necessary)?

**Comment by albertas-jn** [comment]
Ah my mistake, I keep forgetting that `sudo` was removed from the script and I need to add it myself. It works fine.
