### ISSUE TITLE
.env.dist provides empty `SENTRY_DSN` variable

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#769]
It seems that the current .env.dist won't work out of the box: with empty `SENTRY_DSN`, Sentry attempts to connect with `''`, which obviously fails.

IMO we should not make Sentry part of our dev setup, as during development, you'll see errors right away.

**Comment by drikusroor** [comment]
I think it would be better to do a check on whether it's set and if it is, do connect. Similar to how it is done [in the frontend](https://github.com/Amsterdam-Music-Lab/MUSCLE/blob/develop/frontend/src/config/sentry.js).
