### ISSUE TITLE
Introduce validation for `experiment.slug`

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#773]
**Describe the bug**
This is more a bug waiting to happen:

**To Reproduce**
Create an experiment from the admin interface. Give it the slug "admin". Now, when you go to "localhost:3000/admin", you won't get to see your experiment, but instead the admin interface.

**Expected behavior**
* You shouldn't be able to create slugs which conflict with other routes of the interface.
* One additional aspect we might tackle when handling this issue: migrate the field from a `CharField` to a  [SlugField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#slugfield). That means that only letters, numbers, underscores or hyphens are allowed, and will prevent somebody to accidentally type special characters into their slug.
* As discussed in the team meeting of February 27, 2024, we also want to enforce slugs to be lowercase.

**Comment by drikusroor** [comment]
Additionally, should we enforce the slug to be lower case and/or perhaps make it case insensitive? Right now an experiment with the slug `/eurovision` won't be loaded if you navigate to `/Eurovision`

**Comment by BeritJanssen** [comment]
I'm not sure if that's really necessary. Case-sensitivity in urls has been around for a while... @jaburgoyne what do you think?

**Comment by jaburgoyne** [comment]
I am pretty old-school when it comes to naming conventions, and although I think it's great that case-sensitive URLs are possible for the Internet as a whole, I think it's a mistake to rely on them. My ideal world would be case neutrality – i.e., you can type whatever you want, but the slug will always resolve to lowercase – but if that's a hassle to implement, then enforcing lowercase is the next best thing.
