### ISSUE TITLE
Adjust `scripts` so that they can be run with Podman

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#803]
After discussion with @chfin yesterday, we decided that it would be best to adjust the scripts such that `docker compose` is replaced with `podman compose` if the user provides a flag to the script, as setting an alias may be less flexible for users who want to use both Docker and Podman on their system.

**Comment by albertas-jn** [comment]
@BeritJanssen @drikusroor 

Do we still need this? Now that we are moving to Podman based production, shall we all use Podman on development too?
