### ISSUE TITLE
JSON results export is missing participants

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#808]
In the current JSON exports for That's My Song, `results.json` always gives the participant as `null`. This should be the participant ID to facilitate linkage to the other files.

**Comment by Evert-R** [comment]
I just had a quick look at the code, and that does seem right.
`participant` and `session` share the same `Result` object in the database. 

On a session result the participant is `null`. So the route there is: result -> session -> participant
On a participant result the session is `null` and the participant is logged.

This structure is used to seperate session results from participant (profile) results.

**Comment by Evert-R** [comment]
It would be possible to set the participant for the session results in the export function, after the results have already been seperated, if needed.

**Comment by BeritJanssen** [comment]
It's true that without the participant, we cannot connect the data from `result.json` and `participant.json`. Just adding a field of `result.session.participant.id` should do the trick.

**Comment by jaburgoyne** [comment]
Ah, now I see – this is actually a feature and not a bug. To be honest, my feeling now is that we should just close this: do you agree, @Evert-R and @BeritJanssen? It's easy to add the participant ID by joining tables during the analysis, and I think that's cleaner than cluttering the export

**Comment by Evert-R** [comment]
Yes, if it's easy to do this during the analysis, I also think we should leave it the way it is.
