### ISSUE TITLE
Congo matching pairs loads wrong set of stimuli

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#818]
**Describe the bug**
The 16 cards of a matching pairs board are compressed by two sets of 8 stimuli, meaning 8 matches/pairs. In the original condition of the game, the 2 sets of cards are identical, but in the degradation conditions, the first set of 8 cards are original stimuli, and the second set of 8 cards are degraded stimuli. Now, the degradation board will also load the same sets of stimuli occasionally, which means there are no degradation stimuli loaded, but only two sets of original stimuli. This behavior happens randomly when refresh the browser with a degradation game link, sometimes it loads both original and degraded stimuli, sometimes it is two sets of original stimuli, it does not seem to have something to do with Cache. When the cache is cleaned, this bug still appears. 
 

**To Reproduce**
I don't know if it happens on Mac, with the tough book, if you go to any degraded link, and load the game, it can happen anytime. 

**Expected behavior**
The board will load the correct sets of stimuli in the degradation condition, meaning loading 1 set of original stimuli and 1 set of corresponding degraded stimuli to form the game board. 

**Screenshots**

**Desktop (please complete the following information):**

-OS: Windows
-Browser: Firefox 123.0 / Edge 122.0.2365.59

Context 
- see #817

**Comment by BeritJanssen** [comment]
@Lia-JX-Li , I see that we've not updated the logic for selecting stimuli for the `matching_pairs_lite` version. So there is still some logic that presupposes we have a playlist with originals, and two sets of degradations mixed. We'll need to double-check that we redesign the selection of stimuli for `matching_pairs_lite`, with correct assumptions about the playlists coupled to the Congo experiments.
