### ISSUE TITLE
Placeholder for testing and filling the new ACC server with experiments

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#853]
## Requirements

- [x] Download "fixtures" from old ACC
- [x] Download uploads from old ACC
  - I did this using FileZilla and SFTP (SSH File Transfer Protocol)
- [x] Upload uploads to new ACC
  - I did this using FileZilla and SFTP (SSH File Transfer Protocol)
- [x] Update environment variables in Github for new domain (currently set to work with the temporary http://illc-aml-mu-acc.science.uva.nl subdomain)
- [x] Request DNS change
- [x] After DNS confirmation test & confirm everything works as expected on [acc.amsterdammusiclab.nl](acc.amsterdammusiclab.nl)*
- [x] Migrate database

* The new Acceptance environment may seem it is not working when audio sections cannot be loaded, but this is due to #1012 and should be fixed by #1013

**Comment by BeritJanssen** [comment]
The fastest way is probably to export [fixtures](https://docs.djangoproject.com/en/5.0/topics/db/fixtures/) and load them into the new acc server, so we don't have to set up all playlists and experiments by hand.

This would mean we'd have to upload the audio data via `scp`, so `ssh` access to the servers is a prerequisite for this solution.
