### ISSUE TITLE
Customize whether/how number of times played is displayed in dashboard

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#873]
**Is your feature request related to a problem? Please describe.**
As of #872, we have a counter in an `ExperimentCollection` dashboard indicating how often an experiment has been played. We don't want this to be displayed for every dashboard.

**Describe the solution you'd like**
We should introduce a field on `ExperimentCollection` (or related models, see #875 ), a boolean `show_counter`.

**Describe alternatives you've considered**
We could also consider a `CharField` instead, `counter_display_mode`: this could have the options: `[number, none, disable]`. I can imagine that it could be useful for some admin users to set up an experiment in which a dashboard will disable those experiments which have already been played. For Toontjehoger, the display mode should then be `none`, i.e., the information about if and how often an experiment has been played will be ignored.

**Comment by drikusroor** [comment]
Can't we use a Json field named `config` that we can re-use for other things in the future as well without having to migrate? There might be more options that needs to be able to be set, like in #883, #912, and #914.

**Comment by BeritJanssen** [comment]
Hm, I'm not that big a fan of JSON fields. Mind you, for saving extra information about results and sessions they're fine, but for config I would expect them to be too unpredictable. I'd vote for a CharField with different options, which controls whether or not, and if so, which information about sessions is displayed.

**Comment by drikusroor** [comment]
> Hm, I'm not that big a fan of JSON fields. Mind you, for saving extra information about results and sessions they're fine, but for config I would expect them to be too unpredictable. I'd vote for a CharField with different options, which controls whether or not, and if so, which information about sessions is displayed.

Hmm, I would not go for a CharField. The amount of options could increase exponentially when there are more informations to be shown. Perhaps some `BooleanField` like `researcher_mode`, `debug_mode`, `verbose_mode` would make more sense, since we want to show this/these number(s) when the researcher wants to see the started and finished session counts on screen? Either show all or none?

**Comment by BeritJanssen** [comment]
After discussion, we agreed that the number of times played is typically a "as a researcher I want..." type of story, so we should move this information to the admin interface instead.
