### ISSUE TITLE
Every section variant of the playlists of the SameDiff should be randomised

### ISSUE THREAD

**Issue by drikusroor** [Amsterdam-Music-Lab/MUSCLE#919]
The SameDiff experiment collection consists of several experiments. These experiments are all related to a certain musical aspect like beat, rhythm, timbre, melody, etc. Each experiment then consists of two parts: the practice trials and the actual experiment trials. The experiment trials can consist of 4 trials. However, every trial can have 2 or 3 variants of the same musical phrase, in which the original trial has been modified in a certain way. We can refer to these variants as A, B and C.  For every of the 4 trials of an experiment, a variant of the trial should be picked randomly.

## Fully randomized

We can do this the easy way and pick one fully randomised, which is easy, but could potentially lead to some variants to be played more often than others. The distribution might get skewed. There will be around 60 participants so it would be nice to know the risks of this happening. I (Drikus) don't currently have those numbers.

## Factorial design

Alternatively, we could opt for some form of rotation, e.g.:
- Participant 1: 1A 2A 3A 4A
- Participant 1: 1A 2A 3A 4B
- Participant 1: 1A 2A 3A 4C
- Participant 1: 1A 2A 3B 4A
- Participant 1: 1A 2A 3B 4B
- ... and so on

Which might be harder to implement. Perhaps we could do something with using the participant id as a number to base the pattern on. Participant 17 could be the 17th pattern in such a list for example.

## Structure of SameDiff Experiment Collection and its experiments, parts, trials and variants

* Rhythm experiment
  * Practice part
    * Practice trial 1 (only 1 variant, to showcase Same)
    * Practice trial 2 (only 1 variant, to showcase Different)
  * Experiment part
    * Rhythm 1 trial (Variant A, B, or C should be picked randomly)
      * Variant A (Same) => Same - Repetition - _Same_
      * Variant B (Different) Same - Repetition - _Different_
      * Variant C (Different) Same - Repetition - _Different (different in a different way 🙃) _
    * Rhythm 2 trial (Variant A, B, or C should be picked randomly)
      * Variant A (Same)
      * Variant B (Different)
      * Variant C (Different)
    * Rhythm 3 trial (Variant A, B, or C should be picked randomly)
      * Variant A (Same)
      * Variant B (Different)
      * Variant C (Different)
    * Rhythm 4 trial (Variant A, B, or C should be picked randomly)
      * Variant A (Same)
      * Variant B (Different)
      * Variant C (Different)
* Melody experiment
  * ...Practice part & Experiment part
* Beat experiment
  * ...Practice part & Experiment part
* ...Experiment X
* ...Experiment Y

**Comment by Lia-JX-Li** [comment]
Factorial design
Alternatively, we could opt for some form of rotation, e.g.:

_Participant 1: 1A 2B 3C 4A (same, different, different, same)
Participant 2: 1B 2C 3A 4B (different, different, same, different)
Participant 3: 1C 2A 3B 4C (different, same, different, different)
Participant 4: 1A 2B 3C 4A (same, different, different, same) same set with Participant 1
Participant 5: 1B 2C 3A 4B (different, different, same, different) same set with Participant 2_
... and so on
Which might be harder to implement, _but we can then make sure all the stimuli are appro. equally presented_. Perhaps we could do something with using the participant id as a number to base the pattern on. Participant 17 could be the 17th pattern in such a list for example.

Structure of SameDiff Experiment Collection and its experiments, parts, trials and variants
Rhythm experiment (for example)
Practice part
Practice trial 1 (only 1 variant, to showcase Same)
Practice trial 2 (only 1 variant, to showcase Different)
Experiment part
_Rhythm 1 trial (Variant A, B, or C should be picked randomly)
Variant A (Same) => Rhythm 1 - Repetition - Variant A (Same)
Variant B (Different) => Rhythm 1 - Repetition - Variant B (Different-phase)
Variant C (Different) => Rhythm 1 - Repetition - Variant C (Different-period)
Rhythm 2 trial (Variant A, B, or C should be picked randomly)
Variant A (Same) => Rhythm 2 - Repetition - Variant A (Same)
Variant B (Different) => Rhythm 2 - Repetition - Variant B (Different-phase)
Variant C (Different) => Rhythm 2 - Repetition - Variant C (Different-period)
Rhythm 3 trial (Variant A, B, or C should be picked randomly)
Variant A (Same) => Rhythm 3 - Repetition - Variant A (Same)
Variant B (Different) => Rhythm 3 - Repetition - Variant B (Different-phase)
Variant C (Different) => Rhythm 3 - Repetition - Variant C (Different-period)
Rhythm 4 trial (Variant A, B, or C should be picked randomly)
Variant A (Same) => Rhythm 4 - Repetition - Variant A (Same)
Variant B (Different) => Rhythm 4 - Repetition - Variant B (Different-phase)
Variant C (Different) => Rhythm 4 - Repetition - Variant C (Different-period)_
_**Melody experiment**
3 variants
...Practice part & Experiment part
**Beat experiment**
Only 2 variants
...Practice part & Experiment part
**Timbre experiment**
Again 3 variants_
