### ISSUE TITLE
Adding texts to experiments outside Python

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#93]
Currently, if somebody designs an experiment, they need to add instructions, feedback etc. to the user in a Python script. This may put the threshold for using Amsterdam Music Lab too high.

**Comment by drikusroor** [comment]
Why would it take many migrations? Isn't there only one translations table and can't the experiment questions just point to specific translations in that table by id or namespaced slug, e.g. `gmsi.question1`? I'm not (yet) fully up to speed with the current db structure and how experiments are set up so I might overlook a lot of things, but in general, it shouldn't be very hard to add translations. We could even think about supplying the complete list of translations related to an experiment as a json file client-side and use some React library for displaying the correct translation in the correct language based on the user's locale or preference.

As for the amount of work of translating words & sentences: We could also look into crowdsourced translations, making the translations public and allowing users to suggest translations. Or even use GPT's API service for that.

**Comment by BeritJanssen** [comment]
Translations are now added as needed. We would need to add models for any text we want to add via the admin & translate, and the Django plugin adds fields for every language, so that's why we'd need migrations. I've also thought about json/yaml files to use for this.

In general, it's a good idea to use ForeignKey over some reference to ids - faster retrieval, and control over situations in which one part of the database points to information that is gone in another.

**Comment by drikusroor** [comment]
Bump! Let's talk about this again 😸

**Comment by BeritJanssen** [comment]
This issue has been superseded by more specific ones.
