### ISSUE TITLE
Document format of json export (and clean up if applicable)

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#932]
The format of the output for downloading data from the admin interface is not documented anywhere yet. We should add this information for the wiki. Also, if we see fields which are either documented through a rules file, or which are duplicated, in the process, we might still customize the fields which will get exported.

**Comment by Evert-R** [comment]
I've put the documentation of the JSON export in the wiki:
https://github.com/Amsterdam-Music-Lab/MUSCLE/wiki/11.-Exporting-result-data

I couldn't find any duplicated fields, or fields that should be removed. What we export now are the raw django objects related to the sessions, without any modifications. So if any fields in the models are added or removed in the future, we won't have to update the export function. 

Only the `json_data`  fields vary per block/widget/question/trial, but the fields are usually quite self explanatory.

**Comment by Evert-R** [comment]
I just added the manual for the  `CSV export` function to the wiki.
