### ISSUE TITLE
Bug:  the interface shows "end of game" right after clicked "Start"

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#937]
From the Dashboard click a game, and the after pressing the Start, the interface show "end of game" immediately without actually going to the experiment interface, seems like it jumped over the experiment session. Please see video attached.

https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/65351308/e6f99409-d3a3-48e2-9d07-d45ac7776aea

But this can be resolved by refreshing the page.

**Comment by drikusroor** [comment]
Which experiment is this and what playlist csv does it have?

**Comment by Lia-JX-Li** [comment]
It is matching pairs game, btw if the URL shows o-o, o-f1, o-f2, o-t1, o-t2, they are matching pairs game. The game loads when you refresh the page, so I suspect that it's not because of csv, but that some judgement in the rules is conflicting and thus the game is thought to be over so it's skipped!
