### ISSUE TITLE
Add abort button on experiment page to go back to Dashboard 

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#945]
**Is your feature request related to a problem? Please describe.**
As discovered in the dryrun, if we go back to dashboard from a game by clicking the "back" button of the browser, it could cause bugs. This means, we should always use a designed "go back to dashboard" button to go back to dashboard. Now at the end of each game, there is already such a button existing to go back, but not on the other pages of experiment . 

**Describe the solution you'd like**
Would add a very small abort button on the corner solve the problem? So the participant wouldn't accidentally press it, and we could use it if we enter a wrong experiment or an experiment just could not be finished. 

**Alternative**
Or should we just reload the dashboard page URL? Is there some side effect happening with this option?

**Comment by BeritJanssen** [comment]
You can achieve this by reloading the dashboard page URL, indeed. (The participant is not changed, *unless* you reload with another participant id.) So no need to implement an abort button.
