### ISSUE TITLE
BUG: Mathing Pairs rule is not recognizing "heard" correctly

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#949]
The Matching Pairs rule should mark a tile that is heard before and when it is clicked again as a second tile in a Turn, the small feedback at the bottom corner should say "misremembered" if it is not a match, but now it is saying "no match", also for tiles that has been heard before and made a match, the feedback should be "good job" but now it is a "lucky match". It seems like the times "heard" is not recorded or counted correctly, which means that the score we recorded are also wrong. 
This bug has happened before, so hopefully there is a quick fix for this? We need to fix this problem asap.

**Comment by BeritJanssen** [comment]
Note: we need the files & csv of the playlist used for the Congo MatchingPairs experiments.

**Comment by Lia-JX-Li** [comment]
![IMG_1982](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/65351308/09723699-244b-4c16-bece-76c393384834)
Hi Evert, is what I sketched the current setup? This hasn't included the number of times a card is seen though. So could you tell me if there is a file or issue documenting the MP rule, so I can also see how it is set up and if we understand it the same way? Thanks!
