### ISSUE TITLE
Generate audio client-side

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#95]
Currently, audio is precomputed and added as sections. Especially for "just noticeable difference" type experiments it may be useful to generate audio client-side, using the [web audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) or similar.

**Comment by jaburgoyne** [comment]
I am now questioning whether we will ever have the capacity to do this. For me, it is very low priority

**Comment by drikusroor** [comment]
Closed due to low priority / demand.
