### ISSUE TITLE
participant_id_url is not being recorded 

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#959]
Since approximately March 5, the JSON exports erroneously report the participant_id_url as NULL in the That's My Song exports (and presumably would do the same for any other experiment using them). Could these be returned to the export, please?

**Comment by BeritJanssen** [comment]
It seems that this data is actually not saved to the database at the moment. So the export works, but the `?participant_id=` is broken on the version running on production (1.9.0). There were two hotfixes for this in the meantime, but they seem to have not been deployed to production.

**Comment by jaburgoyne** [comment]
If they are not being stored in the database, this is quite a high-priority and urgent issue: it means that the data currently being collected will be unusable for research (or usable only after a complex time/matching process). How difficult will it be to fix?

**Comment by BeritJanssen** [comment]
Fixed as of the lastest release.
