### ISSUE TITLE
Remove `first_round` from rules files

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#973]
After #1132, consent will always be shown via the `consent field` tied to the `Experiment` parent.

Calling the endpoint `block/{id}` will do the following:
- [x] check the participant
- [x] start a session with the current / new participant and the current block, and return its id to the frontend See also #1191

After that, the block will be handled through the `session/{id}/next_round` endpoint
Steps:
**Backend**
- [x] remove Consent actions from all `first_round` methods
- [x] move `Playlist` views to `next_round` (only for those rules where it's conceivable we may have multiple playlists tied to them)
- [x] move every `Explainer` to `next_round`
- [x] remove `first_round` methods
- [ ] do not pass the `next_round` array to the `block` request
~~- [ ] migrate existing Consent forms to Experiment level if applicable~~ -> #1211

**Frontend**
- [ ] remove `Consent` as an option from `Block`
- [ ] adjust `Block` so that it doesn't expect a `next_round` array in the response; instead go to `session/next_round` once created

**Comment by drikusroor** [comment]
> After #1132, consent will always be shown via the `consent field` tied to the `Experiment` parent.

I mean... technically the field is there, but do we have functionality that also checks if the participant has accepted the consent form before starting the experiment / block and shows the consent form if that's not the case? If not, perhaps we should make that before doing this refactor. 🤔
