### ISSUE TITLE
[Congo Matching Pair Quality Control] Card Display in right number

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#984]
As a result of the meeting with Henkjan and Ashley on 30.04. We decided that JL will file the most important three aspects to be tested/quality checked by the MUSCLE team before delivering the product. Please feel free to close the issue after you have checked it. 

First aspect:

When loading the all the matching pairs game, there should be 16 cards of 8 pairs. Not 8 cards or 32 cards. 
JL will attach all the csv files to this issue tomorrow in the morning for @Evert-R to check.

**Comment by Evert-R** [comment]
This is working properly. Only the o-o playlist has 8 sections, because there are no degredations, so these sections are used twice.
